events:
  pull_request:
    - trustAnyone: true
      paths:
      	disallowed:
          - ".github/**"
          - "package.json"
          - "package-lock.json"
          - ".github/protected-workflows.yml" # <-- Exteremly important. Only certain users should be able to change this file.
    
anyEvent:
  trustAnyone: false
  trustCollaborators: true
